# サイト基本情報
title: "Masayuki ABE"         # サイトのタイトル（ブラウザタブにも表示）
name: "Masayuki ABE"          # あなたの名前
email: "abe.masayuki.914@gmail.com"
description: >-           # meta description（Google検索など）
  テスト中です。

# サイトのURL
baseurl: "/"       # サブディレクトリがある場合（GitHub Pages）
#url: "https://nanacov.github.io"

# ソーシャル情報
github_username: nanacov
#twitter_username: your_twitter
orcid_id: "0009-0006-1614-0587"
googlescholar: "https://scholar.google.com/citations?user=sjhfZ_kAAAAJ&hl=en"
#linkedin_username: your-linkedin-id

# ページレイアウトとテーマ
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: default
locale: en-US

# 表示言語など
lang: ja
markdown: kramdown
highlighter: rouge

# Google Analytics（不要なら空に）
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-XXXXXXXX-X"
    anonymize_ip: false

# サイト構造設定
paginate: 10
paginate_path: "/page:num/"

# ナビゲーションの有効化
header_pages:
  - about.md
  - publications.md
  - cv.md
  - teaching.md

# ビルド設定
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true

# MarkdownとLaTeX対応（必要に応じて）
kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
  syntax_highlighter_opts:
    line_numbers: true
